#!/usr/bin/env python3
"""Generate the figures for slide 16 (spread the effort on the lever) and slide 17 (Liebig's plant).
All choreography is SMIL on a fixed loop, so the deck's setCurrentTime(0) restarts it on arrival."""
import pathlib, re
def f(v): return f'{v:.1f}'
# ============ slide 16 · the lever, three rounds of ten units ============
T=20.0
import random
random.seed(11)
def kt(*ts): return ';'.join(f'{t/T:.4f}'.rstrip('0').rstrip('.') if 0<t<T else ('0' if t<=0 else '1') for t in ts)
def yarm(x): return 386+(x-66)*(129-386)/(952-66)
rungs=[(250,333),(311,315),(372,297),(433,280),(494,262),(555,244),(616,227),(677,209),(738,191),(798,174),(859,156),(920,139)]
LOW,MID,HIGH='#fb923c','#5eead4','#c084fc'
def sphere(x, y1, r, t0, color, miss=False, hold=19.5):
    y0=y1-170
    if miss:
        y2=y1+200
        return (f'<circle cx="{f(x)}" cy="{f(y0)}" r="{r}" fill="{color}" opacity="0">'
                f'<animate attributeName="cy" values="{f(y0)};{f(y0)};{f(y1)};{f(y2)};{f(y2)}" keyTimes="{kt(0,t0,t0+.45,t0+1.2,T)}" dur="{T}s" repeatCount="indefinite"/>'
                f'<animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="{kt(0,t0,t0+.05,t0+.7,t0+1.2,T)}" dur="{T}s" repeatCount="indefinite"/></circle>')
    return (f'<circle cx="{f(x)}" cy="{f(y0)}" r="{r}" fill="{color}" opacity="0">'
            f'<animate attributeName="cy" values="{f(y0)};{f(y0)};{f(y1)};{f(y1)}" keyTimes="{kt(0,t0,t0+.45,T)}" dur="{T}s" repeatCount="indefinite"/>'
            f'<animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="{kt(0,t0,t0+.05,hold,hold+.3,T)}" dur="{T}s" repeatCount="indefinite"/></circle>')
# uneven heaps: (centre x, colour, radii of the spheres that land there), plus a few throws at the top that miss
heaps=[(300,LOW,[7,5,8,4]),(360,LOW,[5,6]),(500,MID,[8,6,5,7,4,6]),(590,MID,[5,4]),(690,HIGH,[6,7,5]),(805,HIGH,[7,5,6,4,5]),(880,HIGH,[6,5])]
drops=[]
import math
def settle(cx, radii):
    """Drop spheres one by one near cx; each rests on the arm or on whatever it touches first below."""
    placed=[]; offsets=[0,12,-12,6,-7,0,17,-17,3]
    for k,r in enumerate(radii):
        x=cx+offsets[k%len(offsets)]+random.uniform(-1.5,1.5)
        y=yarm(x)-r-1.75
        for (xj,yj,rj) in placed:
            dx=abs(x-xj)
            if dx<r+rj-0.5:
                y=min(y, yj-math.sqrt((r+rj)**2-dx**2))
        placed.append((x,y,r))
    return placed
for cx,col,radii in heaps:
    for (x,y,r) in settle(cx,radii):
        drops.append((x,y,r,col,False))
for x,r in [(915,6),(935,5),(950,7),(905,4)]:
    drops.append((x,yarm(x)-r,r,HIGH,True))
random.shuffle(drops)
peb=[sphere(x,y,r,0.6+i*0.55,col,miss) for i,(x,y,r,col,miss) in enumerate(drops)]
t_last=0.6+len(drops)*0.55
rot_vals=['0','0','10.5','10.5','0']; rot_times=[0,.6,t_last,19.5,T]
arm_rot=f'<animateTransform attributeName="transform" type="rotate" values="{";".join(v+" 210 344" for v in rot_vals)}" keyTimes="{kt(*rot_times)}" dur="{T}s" repeatCount="indefinite"/>'
ball_tr=f'<animateTransform attributeName="transform" type="translate" values="{";".join("0 "+f(-float(v)*2.6) for v in rot_vals)}" keyTimes="{kt(*rot_times)}" dur="{T}s" repeatCount="indefinite"/>'
def label(txt, t0, t1, color):
    return (f'<g opacity="0"><animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="{kt(0,t0,t0+.4,t1-.3,t1,T)}" dur="{T}s" repeatCount="indefinite"/>'
            f'<text class="lbl-strong" x="60" y="66" style="font-size:15px;fill:{color}">{txt}</text></g>')
rungs_svg=''.join(f'<circle cx="{x}" cy="{y}" r="11" fill="#0d0d15" stroke="rgba(192,132,252,.45)" stroke-width="1.5"/><text x="{x}" y="{y+4}" text-anchor="middle" style="font-size:9.5px;fill:rgba(245,245,247,.6)">{12-i}</text>' for i,(x,y) in enumerate(rungs))
svg16=f'''    <svg class="fig" viewBox="0 0 1000 440" aria-hidden="true" style="max-width:min(1320px,90vw);margin-top:1vh">
      <!-- generated by tools/gen-slide-effort.py — same lever as the previous slide; effort piles up unevenly along it -->
      {label('spread by what the system is short of — big and small, uneven, some at the top will miss', .3, t_last, '#fbbf24')}
      {label('…and it lifts', t_last+.2, 19.6, '#5eead4')}
      <text class="lbl-sm" x="60" y="88" style="font-size:12px;fill:rgba(245,245,247,.55)">the same lever · a finite budget of effort</text>
      <g>
        {arm_rot}
        <line x1="66" y1="386" x2="952" y2="129" stroke="rgba(245,245,247,.7)" stroke-width="3.5" stroke-linecap="round"/>
        <g opacity=".7">{rungs_svg}</g>
        {''.join(peb)}
      </g>
      <polygon points="210,346 186,404 234,404" fill="rgba(255,255,255,.09)" stroke="rgba(245,245,247,.4)" stroke-width="1.5"/>
      <g>
        {ball_tr}
        <circle cx="90" cy="345" r="44" fill="none" stroke="rgba(94,234,212,.6)" stroke-width="2" opacity="0">
          <animate attributeName="opacity" values="0;0;.85;.85;0;0" keyTimes="{kt(0,t_last,t_last+.5,19.3,19.7,T)}" dur="{T}s" repeatCount="indefinite"/>
        </circle>
        <circle cx="90" cy="345" r="36" fill="url(#ballg)"/>
        <text x="90" y="341" text-anchor="middle" style="font-size:13px;font-weight:650;fill:#fff">The</text>
        <text x="90" y="358" text-anchor="middle" style="font-size:13px;font-weight:650;fill:#fff">System</text>
      </g>
      <line x1="150" y1="411" x2="906" y2="411" stroke="rgba(245,245,247,.16)" stroke-width="1.5"/>
      <g style="font-size:10px;letter-spacing:.15em" fill="rgba(245,245,247,.45)">
        <text x="311" y="432" text-anchor="middle">PHYSICAL EVENTS</text>
        <text x="494" y="432" text-anchor="middle">PATTERNS OF BEHAVIOR</text>
        <text x="677" y="432" text-anchor="middle">SYSTEM STRUCTURE</text>
        <text x="859" y="432" text-anchor="middle">MENTAL MODELS</text>
      </g>
    </svg>
'''
# ============ slide 17 · Liebig's plant ============
P=18.0
def kp(*ts): return ';'.join(f'{t/P:.4f}'.rstrip('0').rstrip('.') if 0<t<P else ('0' if t<=0 else '1') for t in ts)
GREEN,YEL,BROWN='#5eead4','#fbbf24','#92400e'
def leaf(cx, cy, side, appear):
    rot=f'{-28*side}'
    return (f'<g opacity="0" transform="rotate(0 {cx} {cy})"><animate attributeName="opacity" values="0;0;1;1;1;0;0" keyTimes="{kp(0,appear,appear+.4,13,15,15.4,P)}" dur="{P}s" repeatCount="indefinite"/>'
            f'<animateTransform attributeName="transform" type="rotate" values="0 {cx} {cy};0 {cx} {cy};0 {cx} {cy};{55*side} {cx} {cy};{55*side} {cx} {cy}" keyTimes="{kp(0,9,13,15,P)}" dur="{P}s" repeatCount="indefinite" additive="replace"/>'
            f'<ellipse cx="{cx+34*side}" cy="{cy}" rx="34" ry="12" fill="{GREEN}" stroke="none" transform="rotate({rot} {cx} {cy})">'
            f'<animate attributeName="fill" values="{GREEN};{GREEN};{GREEN};{YEL};{BROWN};{BROWN}" keyTimes="{kp(0,6,9,12,14.5,P)}" dur="{P}s" repeatCount="indefinite"/></ellipse></g>')
leaves=leaf(300,250,-1,1.2)+leaf(300,222,1,2.2)+leaf(300,194,-1,3.3)+leaf(300,166,1,4.4)+leaf(300,140,-1,5.4)
PINK='#f472b6'
petals=''.join(f'<ellipse cx="0" cy="-15" rx="8" ry="15" fill="{PINK}" transform="rotate({k*60})"><animate attributeName="fill" values="{PINK};{PINK};{PINK};{YEL};{BROWN};{BROWN}" keyTimes="{kp(0,6,9,12,14.5,P)}" dur="{P}s" repeatCount="indefinite"/></ellipse>' for k in range(6))
flower=(f'<g transform="translate(300 118)"><g opacity="0"><animate attributeName="opacity" values="0;0;1;1;1;0;0" keyTimes="{kp(0,5.2,5.6,13,15,15.4,P)}" dur="{P}s" repeatCount="indefinite"/>'
        f'<animateTransform attributeName="transform" type="rotate" values="0;0;0;48;48" keyTimes="{kp(0,9,13,15,P)}" dur="{P}s" repeatCount="indefinite"/>'
        f'<g><animateTransform attributeName="transform" type="scale" values="0;0;1.15;1;1" keyTimes="{kp(0,5.2,6.2,6.6,P)}" dur="{P}s" repeatCount="indefinite"/>'
        f'{petals}<circle r="7" fill="#fbbf24"><animate attributeName="fill" values="#fbbf24;#fbbf24;#fbbf24;#d97706;{BROWN};{BROWN}" keyTimes="{kp(0,6,9,12,14.5,P)}" dur="{P}s" repeatCount="indefinite"/></circle></g></g></g>')
units=''.join(f'<rect x="{560+i*24}" y="272" width="16" height="28" rx="3" fill="rgba(157,185,255,.85)" opacity="0"><animate attributeName="opacity" values="0;0;1;1;0" keyTimes="{kp(0,.6+i*1.35,.9+i*1.35,17.6,P)}" dur="{P}s" repeatCount="indefinite"/><animate attributeName="fill" values="{"rgba(157,185,255,.85)" if i<5 else "#fb7185"};{"rgba(157,185,255,.85)" if i<5 else "#fb7185"}" dur="{P}s" repeatCount="indefinite"/></rect>' for i in range(10))
def phase(txt,t0,t1,color):
    return (f'<g opacity="0"><animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="{kp(0,t0,t0+.4,t1-.3,t1,P)}" dur="{P}s" repeatCount="indefinite"/>'
            f'<text class="lbl-strong" x="300" y="60" text-anchor="middle" style="font-size:15px;fill:{color}">{txt}</text></g>')

# the gardener pours: the can tips once per unit; drops fall to the soil; the soil stains
POUR_T=[0.6+i*1.35 for i in range(10)]
def _kp(*ts): return kp(*ts)
tipv=['0']; tipt=[0.0]
for tp in POUR_T:
    tipv += ['0','-26','-26','0']; tipt += [tp, tp+0.18, tp+0.78, tp+0.95]
tipv.append('0'); tipt.append(P)
can_tip=f'<animateTransform attributeName="transform" type="rotate" values="{';'.join(v+' 470 195' for v in tipv)}" keyTimes="{_kp(*tipt)}" dur="{P}s" repeatCount="indefinite"/>'
drops=''
for i,tp in enumerate(POUR_T):
    col='#9db9ff' if i<5 else '#fb7185'
    for k in range(3):
        t0=tp+0.22+k*0.2; t1=t0+0.42
        drops+=(f'<circle r="3.4" fill="{col}" opacity="0">'
                f'<animateMotion path="M 402 208 Q 392 252 372 296" keyPoints="0;0;1;1" keyTimes="{_kp(0,t0,t1,P)}" calcMode="linear" dur="{P}s" repeatCount="indefinite"/>'
                f'<animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="{_kp(0,t0,t0+0.05,t1-0.05,t1,P)}" dur="{P}s" repeatCount="indefinite"/></circle>')
def stain(idx0,idx1,color,peak):
    vals=['0','0']; ts=[0.0,POUR_T[idx0]]
    n=idx1-idx0+1
    for j in range(n):
        vals.append(f'{peak*(j+1)/n:.2f}'); ts.append(POUR_T[idx0+j]+0.9)
    vals+= [f'{peak:.2f}','0']; ts+=[17.6,P]
    return f'<animate attributeName="opacity" values="{';'.join(vals)}" keyTimes="{_kp(*ts)}" dur="{P}s" repeatCount="indefinite"/>'
soil_blue=f'<rect x="200" y="300" width="200" height="40" rx="8" fill="#9db9ff" opacity="0">{stain(0,4,"x",0.28)}</rect>'
soil_red=f'<rect x="200" y="300" width="200" height="40" rx="8" fill="#fb7185" opacity="0">{stain(5,9,"x",0.42)}</rect>'
pour_rig=f'''
      <!-- the gardener pours: nitrogen, one canful per unit -->
      {soil_blue}
      {soil_red}
      <g>
        {can_tip}
        <rect x="440" y="170" width="64" height="46" rx="10" fill="rgba(157,185,255,.14)" stroke="rgba(157,185,255,.8)" stroke-width="2"/>
        <path d="M 444 178 L 404 200 L 412 210 L 448 194 Z" fill="rgba(157,185,255,.14)" stroke="rgba(157,185,255,.8)" stroke-width="2" stroke-linejoin="round"/>
        <path d="M 500 178 a 16 16 0 0 1 0 30" fill="none" stroke="rgba(157,185,255,.8)" stroke-width="2"/>
        <text class="lbl-sm" x="472" y="198" text-anchor="middle" style="fill:#9db9ff;font-weight:650">nitrogen</text>
      </g>
      {drops}
      <g opacity="0"><animate attributeName="opacity" values="0;0;1;1;0" keyTimes="{_kp(0,6.6,7.1,17.4,P)}" dur="{P}s" repeatCount="indefinite"/>
        <text class="lbl-sm" x="560" y="140" text-anchor="middle" style="fill:rgba(94,234,212,.9)">enough — after five pours, nitrogen stopped being the limit</text></g>
      <!-- the bag that never pours -->
      <g>
        <path d="M 560 336 q -4 -26 10 -30 h 36 q 14 4 10 30 z" fill="rgba(251,113,133,.12)" stroke="rgba(251,113,133,.75)" stroke-width="2" stroke-linejoin="round"/>
        <path d="M 568 306 q 20 -10 40 0" fill="none" stroke="rgba(251,113,133,.75)" stroke-width="2"/>
        <text class="lbl-sm" x="588" y="328" text-anchor="middle" style="fill:#fda4af;font-weight:650">K</text>
      </g>
      <text class="lbl-sm" x="560" y="368" style="font-size:12px;fill:#fda4af">potassium — short, the whole time</text>
'''
svg17=f'''    <svg class="fig" viewBox="0 0 900 400" aria-hidden="true" style="max-width:min(1100px,80vw);margin-top:1vh">
      <!-- generated by tools/gen-slide-effort.py — nitrogen unit by unit, potassium short -->
      {phase('growing — every unit helps', .4, 6.2, GREEN)}
      {phase('no longer the constraint — nothing happens', 6.4, 9.2, 'rgba(245,245,247,.8)')}
      {phase('excess — drying out', 9.4, 13.2, YEL)}
      {phase('dead', 13.4, 17.6, '#fb7185')}
      <!-- soil and plant -->
      <rect x="200" y="300" width="200" height="40" rx="8" fill="rgba(196,150,110,.28)" stroke="rgba(196,150,110,.6)"/>
      <line x1="300" y1="300" x2="300" y2="300" stroke="{GREEN}" stroke-width="6" stroke-linecap="round">
        <animate attributeName="y2" values="300;300;120;120;120;140;140" keyTimes="{kp(0,.4,6,9,13,15,P)}" dur="{P}s" repeatCount="indefinite"/>
        <animate attributeName="stroke" values="{GREEN};{GREEN};{GREEN};{YEL};{BROWN};{BROWN}" keyTimes="{kp(0,6,9,12,14.5,P)}" dur="{P}s" repeatCount="indefinite"/>
      </line>
      {leaves}
      {flower}
{pour_rig}
    </svg>
'''
p=pathlib.Path(__file__).resolve().parent.parent/'presentation.html'; s=p.read_text()
for marker,nxt,svg in [('18 · SPREAD THE EFFORT =====','19 · LIEBIG =====',svg16),('19 · LIEBIG =====','20 · SYSTEM TRAPS',svg17)]:
    i=s.index(marker); j=s.index(nxt); seg=s[i:j]; a=seg.index('    <svg class="fig"'); b=seg.index('</svg>',a)+len('</svg>\n')
    s=s[:i]+seg[:a]+svg+seg[b:]+s[j:]
p.write_text(s); print('figures regenerated')
