#!/usr/bin/env python3
"""Generate the figures for slide 16 (spread the effort on the lever) and slide 17 (Liebig's plant).
All choreography is SMIL on a fixed loop, so the deck's setCurrentTime(0) restarts it on arrival."""
import pathlib, re
def f(v): return f'{v:.1f}'
# ============ slide 16 · the lever, three rounds of ten units ============
T=30.0
def kt(*ts): return ';'.join(f'{t/T:.4f}'.rstrip('0').rstrip('.') if 0<t<T else ('0' if t<=0 else '1') for t in ts)
def yarm(x): return 386+(x-66)*(129-386)/(952-66)
rungs=[(250,333),(311,315),(372,297),(433,280),(494,262),(555,244),(616,227),(677,209),(738,191),(798,174),(859,156),(920,139)]
def pebble(x, t0, land, color, miss=False):
    ya=yarm(x); y0=ya-150; y1=ya-7
    if miss:
        y2=ya+190
        return (f'<circle cx="{f(x)}" cy="{f(y0)}" r="5" fill="{color}" opacity="0">'
                f'<animate attributeName="cy" values="{f(y0)};{f(y0)};{f(y1)};{f(y2)};{f(y2)}" keyTimes="{kt(0,t0,t0+.45,t0+1.1,T)}" dur="{T}s" repeatCount="indefinite"/>'
                f'<animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="{kt(0,t0,t0+.05,t0+.6,t0+1.1,T)}" dur="{T}s" repeatCount="indefinite"/></circle>')
    return (f'<circle cx="{f(x)}" cy="{f(y0)}" r="5" fill="{color}" opacity="0">'
            f'<animate attributeName="cy" values="{f(y0)};{f(y0)};{f(y1)};{f(y1)}" keyTimes="{kt(0,t0,t0+.45,T)}" dur="{T}s" repeatCount="indefinite"/>'
            f'<animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="{kt(0,t0,t0+.05,land,land+.3,T)}" dur="{T}s" repeatCount="indefinite"/></circle>')
LOW,MID,HIGH='#fb923c','#5eead4','#c084fc'
peb=[]
# round 1 · 0–8 s : all low
for i,x in enumerate([240+i*9 for i in range(10)]): peb.append(pebble(x, .6+i*.6, 8.0, LOW))
# round 2 · 8.3–16 s : all high — 8 miss, 2 land
hi_land=[905,925]; hi_miss=[862,878,893,940,956,970,986,848]
seq=[(hi_miss[0],False),(hi_miss[1],False),(hi_land[0],True),(hi_miss[2],False),(hi_miss[3],False),(hi_miss[4],False),(hi_land[1],True),(hi_miss[5],False),(hi_miss[6],False),(hi_miss[7],False)]
for i,(x,hit) in enumerate(seq): peb.append(pebble(x, 8.8+i*.6, 16.0, HIGH, miss=not hit))
# round 3 · 16.3–26 s : spread — 3 low, 4 mid, 3 high (one high miss)
spread=[(262,LOW,True),(302,LOW,True),(342,LOW,True),(482,MID,True),(542,MID,True),(602,MID,True),(662,MID,True),(800,HIGH,True),(918,HIGH,False),(862,HIGH,True)]
for i,(x,c,hit) in enumerate(spread): peb.append(pebble(x, 16.8+i*.7, 29.5, c, miss=not hit))
rot=f'values="0;0;1.2;1.2;0;0;3.6;3.6;0;0;10.5;10.5;10.5;0" keyTimes="{kt(0,.6,8,8.1,8.4,8.8,16,16.1,16.4,16.8,24.5,26,29.5,T)}"'
rot_vals=rot.replace('values="','').split('"')[0]; rot_kt=rot.split('keyTimes="')[1].split('"')[0]
arm_rot=f'<animateTransform attributeName="transform" type="rotate" values="{";".join(v+" 210 344" for v in rot_vals.split(";"))}" keyTimes="{rot_kt}" dur="{T}s" repeatCount="indefinite"/>'
ball_tr=f'<animateTransform attributeName="transform" type="translate" values="{";".join("0 "+f(-float(v)*2.6) for v in rot_vals.split(";"))}" keyTimes="{rot_kt}" dur="{T}s" repeatCount="indefinite"/>'
def label(txt, t0, t1, color):
    return (f'<g opacity="0"><animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="{kt(0,t0,t0+.4,t1-.3,t1,T)}" dur="{T}s" repeatCount="indefinite"/>'
            f'<text class="lbl-strong" x="60" y="66" style="font-size:15px;fill:{color}">{txt}</text></g>')
rungs_svg=''.join(f'<circle cx="{x}" cy="{y}" r="11" fill="#0d0d15" stroke="rgba(192,132,252,.45)" stroke-width="1.5"/><text x="{x}" y="{y+4}" text-anchor="middle" style="font-size:9.5px;fill:rgba(245,245,247,.6)">{12-i}</text>' for i,(x,y) in enumerate(rungs))
svg16=f'''    <svg class="fig" viewBox="0 0 1000 440" aria-hidden="true" style="max-width:min(1320px,90vw);margin-top:1vh">
      <!-- generated by tools/gen-slide-effort.py — same lever as the previous slide, ten units, three rounds -->
      {label('round 1 — all ten units low: it barely moves', .3, 8.3, LOW)}
      {label('round 2 — all ten at the top: most bounce off', 8.5, 16.3, HIGH)}
      {label('round 3 — the same ten, spread by what is short: it lifts', 16.5, 29.6, '#fbbf24')}
      <text class="lbl-sm" x="60" y="88" style="font-size:12px;fill:rgba(245,245,247,.55)">ten units of effort · same lever · same system</text>
      <g>
        {arm_rot}
        <line x1="66" y1="386" x2="952" y2="129" stroke="rgba(245,245,247,.7)" stroke-width="3.5" stroke-linecap="round"/>
        <g opacity=".7">{rungs_svg}</g>
        {''.join(peb)}
      </g>
      <polygon points="210,346 186,404 234,404" fill="rgba(255,255,255,.09)" stroke="rgba(245,245,247,.4)" stroke-width="1.5"/>
      <g>
        {ball_tr}
        <circle cx="90" cy="345" r="44" fill="none" stroke="rgba(94,234,212,.6)" stroke-width="2" opacity="0">
          <animate attributeName="opacity" values="0;0;.85;.85;0;0" keyTimes="{kt(0,24.5,25,29,29.6,T)}" dur="{T}s" repeatCount="indefinite"/>
        </circle>
        <circle cx="90" cy="345" r="36" fill="url(#ballg)"/>
        <text x="90" y="341" text-anchor="middle" style="font-size:13px;font-weight:650;fill:#fff">The</text>
        <text x="90" y="358" text-anchor="middle" style="font-size:13px;font-weight:650;fill:#fff">System</text>
      </g>
      <line x1="150" y1="411" x2="906" y2="411" stroke="rgba(245,245,247,.16)" stroke-width="1.5"/>
      <g style="font-size:10px;letter-spacing:.15em" fill="rgba(245,245,247,.45)">
        <text x="311" y="432" text-anchor="middle">PHYSICAL EVENTS</text>
        <text x="494" y="432" text-anchor="middle">PATTERNS OF BEHAVIOR</text>
        <text x="677" y="432" text-anchor="middle">SYSTEM STRUCTURE</text>
        <text x="859" y="432" text-anchor="middle">MENTAL MODELS</text>
      </g>
    </svg>
'''
# ============ slide 17 · Liebig's plant ============
P=18.0
def kp(*ts): return ';'.join(f'{t/P:.4f}'.rstrip('0').rstrip('.') if 0<t<P else ('0' if t<=0 else '1') for t in ts)
GREEN,YEL,BROWN='#5eead4','#fbbf24','#92400e'
def leaf(cx, cy, side, appear):
    rot=f'{-28*side}'
    return (f'<g opacity="0" transform="rotate(0 {cx} {cy})"><animate attributeName="opacity" values="0;0;1;1;1;0;0" keyTimes="{kp(0,appear,appear+.4,13,15,15.4,P)}" dur="{P}s" repeatCount="indefinite"/>'
            f'<animateTransform attributeName="transform" type="rotate" values="0 {cx} {cy};0 {cx} {cy};0 {cx} {cy};{55*side} {cx} {cy};{55*side} {cx} {cy}" keyTimes="{kp(0,9,13,15,P)}" dur="{P}s" repeatCount="indefinite" additive="replace"/>'
            f'<ellipse cx="{cx+34*side}" cy="{cy}" rx="34" ry="12" fill="{GREEN}" stroke="none" transform="rotate({rot} {cx} {cy})">'
            f'<animate attributeName="fill" values="{GREEN};{GREEN};{GREEN};{YEL};{BROWN};{BROWN}" keyTimes="{kp(0,6,9,12,14.5,P)}" dur="{P}s" repeatCount="indefinite"/></ellipse></g>')
leaves=leaf(300,250,-1,1.2)+leaf(300,222,1,2.2)+leaf(300,194,-1,3.3)+leaf(300,166,1,4.4)+leaf(300,140,-1,5.4)
units=''.join(f'<rect x="{560+i*24}" y="272" width="16" height="28" rx="3" fill="rgba(157,185,255,.85)" opacity="0"><animate attributeName="opacity" values="0;0;1;1;0" keyTimes="{kp(0,.6+i*1.35,.9+i*1.35,17.6,P)}" dur="{P}s" repeatCount="indefinite"/><animate attributeName="fill" values="{"rgba(157,185,255,.85)" if i<5 else "#fb7185"};{"rgba(157,185,255,.85)" if i<5 else "#fb7185"}" dur="{P}s" repeatCount="indefinite"/></rect>' for i in range(10))
def phase(txt,t0,t1,color):
    return (f'<g opacity="0"><animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="{kp(0,t0,t0+.4,t1-.3,t1,P)}" dur="{P}s" repeatCount="indefinite"/>'
            f'<text class="lbl-strong" x="300" y="60" text-anchor="middle" style="font-size:15px;fill:{color}">{txt}</text></g>')
svg17=f'''    <svg class="fig" viewBox="0 0 900 400" aria-hidden="true" style="max-width:min(1100px,80vw);margin-top:1vh">
      <!-- generated by tools/gen-slide-effort.py — nitrogen unit by unit, potassium short -->
      {phase('growing — every unit helps', .4, 6.2, GREEN)}
      {phase('no longer the constraint — nothing happens', 6.4, 9.2, 'rgba(245,245,247,.8)')}
      {phase('excess — drying out', 9.4, 13.2, YEL)}
      {phase('dead', 13.4, 17.6, '#fb7185')}
      <!-- soil and plant -->
      <rect x="200" y="300" width="200" height="40" rx="8" fill="rgba(196,150,110,.28)" stroke="rgba(196,150,110,.6)"/>
      <line x1="300" y1="300" x2="300" y2="300" stroke="{GREEN}" stroke-width="6" stroke-linecap="round">
        <animate attributeName="y2" values="300;300;120;120;120;140;140" keyTimes="{kp(0,.4,6,9,13,15,P)}" dur="{P}s" repeatCount="indefinite"/>
        <animate attributeName="stroke" values="{GREEN};{GREEN};{GREEN};{YEL};{BROWN};{BROWN}" keyTimes="{kp(0,6,9,12,14.5,P)}" dur="{P}s" repeatCount="indefinite"/>
      </line>
      {leaves}
      <!-- nutrients -->
      <text class="lbl-sm" x="560" y="250" style="font-size:12px">nitrogen added, one unit at a time</text>
      {units}
      <line x1="560" y1="264" x2="800" y2="264" stroke="rgba(245,245,247,.15)"/>
      <line x1="676" y1="258" x2="676" y2="306" stroke="rgba(94,234,212,.7)" stroke-width="1.5" stroke-dasharray="4 4"/>
      <text class="lbl-sm" x="676" y="322" text-anchor="middle" style="font-size:11px;fill:rgba(94,234,212,.9)">enough — the plant stopped being nitrogen-limited here</text>
      <rect x="560" y="340" width="240" height="14" rx="7" fill="rgba(255,255,255,.05)" stroke="rgba(245,245,247,.25)"/>
      <rect x="560" y="340" width="52" height="14" rx="7" fill="#fb7185"/>
      <text class="lbl-sm" x="560" y="372" style="font-size:12px;fill:#fda4af">potassium — short, the whole time</text>
    </svg>
'''
p=pathlib.Path(__file__).resolve().parent.parent/'presentation.html'; s=p.read_text()
for marker,nxt,svg in [('16 · SPREAD THE EFFORT =====','17 · LIEBIG =====',svg16),('17 · LIEBIG =====','18 · PARADIGMS',svg17)]:
    i=s.index(marker); j=s.index(nxt); seg=s[i:j]; a=seg.index('    <svg class="fig"'); b=seg.index('</svg>',a)+len('</svg>\n')
    s=s[:i]+seg[:a]+svg+seg[b:]+s[j:]
p.write_text(s); print('figures regenerated')
