#!/usr/bin/env python3
"""Regenerate the 2.5D pitch/court figure on slide 4 (Elements · Interconnections · Purpose).

The ground plane (x = width 50..590, y = depth 50 far .. 330 near, in the old flat
coordinates) is projected into perspective; players stand as pins. Tweak the knobs
below and run:  python3 tools/gen-slide4.py
"""
import math, pathlib, re

# ---- knobs ----
NEAR_Y, FAR_Y = 344, 46          # screen y of the near / far touchline (viewBox is 680×384)
NEAR_HALF_W = 316                # half width of the near touchline (centre x = 320)
FAR_SHRINK = 0.42                # far touchline is (1-FAR_SHRINK) as wide as the near one
PIN = 26                         # pin height
GOAL_H, HOOP_H = 36, 48

def P(x, y):
    d = (330 - y) / 280.0
    s = 1 - FAR_SHRINK * d
    return (320 + (x - 320) * (NEAR_HALF_W / 270.0) * s, NEAR_Y - d * (NEAR_Y - FAR_Y))
def f(v): return f'{v:.1f}'
def poly(points): return ' '.join(f'{f(X)},{f(Y)}' for X, Y in points)
def path_from(points, close=False):
    return 'M ' + ' L '.join(f'{f(X)} {f(Y)}' for X, Y in points) + (' Z' if close else '')
def circle_path(cx, cy, r, n=40):
    return path_from([P(cx + r*math.cos(2*math.pi*i/n), cy + r*math.sin(2*math.pi*i/n)) for i in range(n)], True)
def curve_pts(p0, c, p1, n=18):
    return [P((1-t)**2*p0[0] + 2*(1-t)*t*c[0] + t**2*p1[0], (1-t)**2*p0[1] + 2*(1-t)*t*c[1] + t**2*p1[1]) for t in (i/n for i in range(n+1))]
def ground(x, y): return P(x, y)
def head(x, y): X, Y = P(x, y); return (X, Y - PIN)
def seg_path(seq, use_head): return 'M ' + ' L '.join(f'{f(X)} {f(Y)}' for X, Y in (head(*p) if use_head else ground(*p) for p in seq))
def lines(seq, use_head, extra=''):
    pts = [head(*p) if use_head else ground(*p) for p in seq]
    return '\n            '.join(f'<line class="flowdash{extra}" x1="{f(a[0])}" y1="{f(a[1])}" x2="{f(b[0])}" y2="{f(b[1])}"/>' for a, b in zip(pts, pts[1:]))

corners = [P(50,50), P(590,50), P(590,330), P(50,330)]
players = [(120,210,'Ana','Sofia'),(210,110,'Ion','Andrei'),(262,262,'Mara','Ioana'),(398,150,'Dan','Matei'),(487,246,'Vlad','Elena'),(450,86,'Ilinca','Petru'),(150,300,'Tudor','Irina')]
fb = [(120,210),(210,110),(262,262),(398,150),(487,246),(598,190)]
bb = [(150,300),(262,262),(398,150),(487,246),(450,86)]
lb = [(450,86),(398,150),(262,262),(210,110),(120,210)]
def ring(x, y): gx, gy = P(x, y); return gx, gy, (gx, gy - HOOP_H)
rx_g, ry_g, right_top = ring(564,190); lx_g, ly_g, left_top = ring(76,190)
p_shot = head(450,86); shot_ctrl = ((p_shot[0]+right_top[0])/2, min(p_shot[1], right_top[1]) - 70)
shot = f'M {f(p_shot[0])} {f(p_shot[1])} Q {f(shot_ctrl[0])} {f(shot_ctrl[1])} {f(right_top[0])} {f(right_top[1])}'
p_own = head(120,210); own_ctrl = ((p_own[0]+left_top[0])/2, min(p_own[1], left_top[1]) - 55)
own = f'M {f(p_own[0])} {f(p_own[1])} Q {f(own_ctrl[0])} {f(own_ctrl[1])} {f(left_top[0])} {f(left_top[1])}'
g1 = P(590,158); g2 = P(590,222)
arcL = curve_pts((50,110),(200,190),(50,270)); arcR = curve_pts((590,110),(440,190),(590,270))
pins, namesA, namesB = [], [], []
for i, (x, y, a, b) in enumerate(players):
    gx, gy = P(x, y); hx, hy = head(x, y)
    pins.append(f'''        <g class="pop" style="--d:{0.5+0.07*i:.2f}s">
          <ellipse cx="{f(gx)}" cy="{f(gy)}" rx="9" ry="3.2" fill="rgba(0,0,0,.45)"/>
          <line x1="{f(gx)}" y1="{f(gy)}" x2="{f(hx)}" y2="{f(hy)}" stroke="rgba(122,162,255,.55)" stroke-width="2"/>
          <circle cx="{f(hx)}" cy="{f(hy)}" r="8.5" fill="#7aa2ff"/>
        </g>''')
    namesA.append(f'<text data-ro="{a}" x="{f(hx)}" y="{f(hy-14)}" text-anchor="middle">{a}</text>')
    namesB.append(f'<text data-ro="{b}" x="{f(hx)}" y="{f(hy-14)}" text-anchor="middle">{b}</text>')
cx_far = P(320,50); cx_near = P(320,330)
svg = f'''    <svg class="fig sysfig" viewBox="0 0 680 384" aria-hidden="true" style="margin-top:.6vh;max-width:min(760px,56vw)">
      <!-- 2.5D (generated by tools/gen-slide4.py): the ground plane is projected, players stand as pins -->
      <defs>
        <linearGradient id="pitchg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="rgba(94,234,212,.04)"/><stop offset="1" stop-color="rgba(94,234,212,.12)"/></linearGradient>
        <linearGradient id="courtg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="rgba(251,146,60,.05)"/><stop offset="1" stop-color="rgba(251,146,60,.16)"/></linearGradient>
      </defs>
      <!-- ACT 0/1 · football pitch -->
      <g class="fadein" style="--d:.3s">
        <g class="g-football">
          <polygon points="{poly(corners)}" fill="url(#pitchg)" stroke="rgba(94,234,212,.45)" stroke-width="1.5"/>
          <line x1="{f(cx_far[0])}" y1="{f(cx_far[1])}" x2="{f(cx_near[0])}" y2="{f(cx_near[1])}" stroke="rgba(94,234,212,.25)"/>
          <path d="{circle_path(320,190,42)}" fill="none" stroke="rgba(94,234,212,.25)"/>
          <path d="{path_from([P(50,120),P(96,120),P(96,260),P(50,260)])}" fill="none" stroke="rgba(94,234,212,.22)"/>
          <path d="{path_from([P(590,120),P(544,120),P(544,260),P(590,260)])}" fill="none" stroke="rgba(94,234,212,.22)"/>
          <g class="draw" pathLength="1" style="--d:.7s" fill="none" stroke="#fbbf24" stroke-width="2.5">
            <path d="M {f(g1[0])} {f(g1[1])} v -{GOAL_H} L {f(g2[0])} {f(g2[1]-GOAL_H)} v {GOAL_H}"/>
          </g>
          <path d="M {f(g1[0])} {f(g1[1]-GOAL_H)} l 14 -6 v {GOAL_H} l -14 6 M {f(g2[0])} {f(g2[1]-GOAL_H)} l 14 -6 v {GOAL_H} l -14 6" fill="rgba(251,191,36,.08)" stroke="rgba(251,191,36,.35)"/>
          <g stroke="rgba(140,175,255,.75)" stroke-width="2" fill="none">
            {lines(fb, False, ' fadein')}
          </g>
          <g class="fadein" style="--d:1.7s">
            <circle r="5" fill="#f5f5f7">
              <animateMotion dur="5.5s" repeatCount="indefinite" path="{seg_path(fb, False)}"/>
              <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;.04;.94;1" dur="5.5s" repeatCount="indefinite"/>
            </circle>
          </g>
          <circle class="pulse" cx="{f(P(598,190)[0])}" cy="{f(P(598,190)[1])}" r="8" fill="none" stroke="#fbbf24" stroke-width="1.5" style="--d:2.2s"/>
        </g>
      </g>
      <!-- ACT 2/3 · basketball court, two hoops standing at the ends -->
      <g class="g-court">
        <polygon points="{poly(corners)}" fill="url(#courtg)" stroke="rgba(251,146,60,.5)" stroke-width="1.5"/>
        <line x1="{f(cx_far[0])}" y1="{f(cx_far[1])}" x2="{f(cx_near[0])}" y2="{f(cx_near[1])}" stroke="rgba(251,146,60,.25)"/>
        <path d="{circle_path(320,190,36)}" fill="none" stroke="rgba(251,146,60,.25)"/>
        <path d="{path_from(arcL)}" fill="none" stroke="rgba(251,146,60,.25)"/>
        <path d="{path_from(arcR)}" fill="none" stroke="rgba(251,146,60,.25)"/>
        <g stroke="#fbbf24" stroke-width="2.5" fill="none">
          <line x1="{f(lx_g)}" y1="{f(ly_g)}" x2="{f(left_top[0])}" y2="{f(left_top[1]+6)}"/><ellipse cx="{f(left_top[0])}" cy="{f(left_top[1])}" rx="9" ry="3.4"/>
          <line x1="{f(rx_g)}" y1="{f(ry_g)}" x2="{f(right_top[0])}" y2="{f(right_top[1]+6)}"/><ellipse cx="{f(right_top[0])}" cy="{f(right_top[1])}" rx="9" ry="3.4"/>
        </g>
      </g>
      <!-- act 2: passes at chest height, then a shot on the far ring -->
      <g class="g-bpass">
        <g stroke="rgba(251,146,60,.8)" stroke-width="2" fill="none">
          {lines(bb, True)}
          <path class="flowdash" d="{shot}"/>
        </g>
        <circle r="5.5" fill="#fdba74">
          <animateMotion dur="5s" repeatCount="indefinite" path="{seg_path(bb, True)} {shot.split(' ',3)[3]}"/>
          <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;.04;.94;1" dur="5s" repeatCount="indefinite"/>
        </circle>
        <circle class="softpulse" cx="{f(right_top[0])}" cy="{f(right_top[1])}" r="11" fill="none" stroke="#fbbf24" stroke-width="1.5"/>
      </g>
      <!-- act 3: same players, same rules — the ball goes into the OWN ring -->
      <g class="g-lpass">
        <g stroke="rgba(251,113,133,.85)" stroke-width="2" fill="none">
          {lines(lb, True)}
          <path class="flowdash" d="{own}"/>
        </g>
        <circle r="5.5" fill="#fda4af">
          <animateMotion dur="5s" repeatCount="indefinite" path="{seg_path(lb, True)} {own.split(' ',3)[3]}"/>
          <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;.04;.94;1" dur="5s" repeatCount="indefinite"/>
        </circle>
        <text class="lbl-sm" x="320" y="{NEAR_Y+17}" text-anchor="middle" style="fill:#fda4af;font-weight:650">purpose: lose the game</text>
        <text class="lbl-sm" x="{f(left_top[0])}" y="{f(left_top[1]-14)}" text-anchor="middle" style="fill:#fda4af">own basket</text>
      </g>
      <!-- the players — the same seven pins in every act -->
      <g>
{chr(10).join(pins)}
      </g>
      <g class="names names-a" style="font-size:10.5px;fill:rgba(157,185,255,.9)">
        {' '.join(namesA)}
      </g>
      <g class="names names-b" style="font-size:10.5px;fill:rgba(157,185,255,.9)">
        {' '.join(namesB)}
      </g>
      <!-- the reading -->
      <g style="font-size:13px">
        <text class="fadein" x="4" y="{NEAR_Y+34}" style="--d:2s;fill:#9db9ff"><tspan style="font-weight:650">elements</tspan> — players</text>
        <text class="fadein" x="320" y="{NEAR_Y+34}" text-anchor="middle" style="--d:2.2s;fill:#7fe7d4"><tspan style="font-weight:650">interconnections</tspan> — passes</text>
        <text class="fadein" x="676" y="{NEAR_Y+34}" text-anchor="end" style="--d:2.4s;fill:#fbbf24"><tspan style="font-weight:650">purpose</tspan> — score</text>
      </g>
    </svg>
'''
p = pathlib.Path(__file__).resolve().parent.parent / 'presentation.html'; s = p.read_text()
i = s.index('4 · WHAT IS A SYSTEM ====='); j = s.index('5 · STOCKS & FLOWS =====')
seg = s[i:j]; a = seg.index('    <svg class="fig sysfig"'); b = seg.index('</svg>', a) + len('</svg>\n')
s = s[:i] + seg[:a] + svg + seg[b:] + s[j:]; p.write_text(s)
print('slide 4 figure regenerated; far touchline', [round(v) for v in P(50,50)], 'near', [round(v) for v in P(50,330)])
